version: '3.8'

services:
  autotrade:
    build: .
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env  # 환경 변수 파일 로드
    environment:
      - MONGO_URI=mongodb://mongo:27017/autotrade_db
    depends_on:
      - mongo
    restart: unless-stopped
    # 명시적으로 scheduler.py 실행 (선택 사항)
    # command: ["python", "scheduler.py"]

  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=autotrade_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data:
