# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bitcoin_trades_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"  # 필요 시 외부 접속을 허용

  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile.trading_bot
    container_name: trading_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - trading_network

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    restart: always
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    networks:
      - trading_network

volumes:
  mongo_data:

networks:
  trading_network:
    driver: bridge
